blueprint:
  name: "TX-Ultimate-Easy Enhanced Boot Restorer"
  description: |
    ### (Version: 1.3.7)
    
    This blueprint acts as a comprehensive dynamic management layer for the **TX-Ultimate-Easy** (by edwardtfn). While the ESPHome firmware handles local hardware logic, this blueprint provides:
    
    * **1. Dynamic Boot Logic (Internal)**: Set relay boot states (On/Off) directly within this configuration. No external helpers required.
    * **2. Reconnection Sync**: Automatically restores states when the device recovers from an 'unavailable' state.
    * **3. Parallel Processing**: All 4 channels operate independently. A delay on one channel will not block the others.
    * **4. Intelligent Timing & Availability**: 
        * **Initial Delay**: Stability wait after the T5 boots (Optimized Range: 0-10s).
        * **Smart Wait**: Waits for the linked device to become "available" before syncing (Optimized Range: 0-30s).
    * **5. Fault-Tolerant Sync**: Linked device actions are non-blocking. If a command fails (e.g., Matter timeout), the automation continues without erroring out.
    * **6. Stealth Mode (Status Cleanup)**: Automatically turns off the LED ring indicator after all sequences complete.
    
    ---
    **Note**: Supports 1 to 4 channels. Unused channels can be left blank.
  domain: automation
  source_url: https://github.com/MarcusTseng/tx-ultimate-relay-boot-mode/blob/main/blueprints/automation/tx_boot_mode/tx_relay_boot_mode.yaml
  author: Marcus Tseng
  homeassistant:
    min_version: 2025.12.0
  input:
    trigger_sensor:
      name: Device Connectivity Sensor
      description: The 'Device Name' sensor provided by TX-Ultimate-Easy.
      selector:
        entity:
          domain: sensor
    initial_delay:
      name: Initial Delay
      description: Wait time after T5 comes online before triggering relays.
      default: 5
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: seconds
          mode: slider
    sync_delay:
      name: Linked Device Wait Timeout
      description: Maximum time to wait for each linked device to become "available".
      default: 15
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: seconds
          mode: slider
    relay_1_switch:
      name: Relay 1 Switch
      selector:
        entity:
          domain: [switch, light]
    relay_1_mode:
      name: Relay 1 Boot Mode
      default: "off"
      selector:
        select:
          options:
            - label: "On"
              value: "on"
            - label: "Off"
              value: "off"
    linked_device_1:
      name: Relay 1 Linked External Device
      default: []
      selector:
        entity: {}
    keep_linked_1_on:
      name: Keep Linked Device 1 ON?
      default: true
      selector:
        boolean: {}
    relay_2_switch:
      name: Relay 2 Switch
      default: []
      selector:
        entity:
          domain: [switch, light]
    relay_2_mode:
      name: Relay 2 Boot Mode
      default: "off"
      selector:
        select:
          options:
            - label: "On"
              value: "on"
            - label: "Off"
              value: "off"
    linked_device_2:
      name: Relay 2 Linked External Device
      default: []
      selector:
        entity: {}
    keep_linked_2_on:
      name: Keep Linked Device 2 ON?
      default: true
      selector:
        boolean: {}
    relay_3_switch:
      name: Relay 3 Switch 
      default: []
      selector:
        entity:
          domain: [switch, light]
    relay_3_mode:
      name: Relay 3 Boot Mode
      default: "off"
      selector:
        select:
          options:
            - label: "On"
              value: "on"
            - label: "Off"
              value: "off"
    linked_device_3:
      name: Relay 3 Linked External Device
      default: []
      selector:
        entity: {}
    keep_linked_3_on:
      name: Keep Linked Device 3 ON?
      default: true
      selector:
        boolean: {}
    relay_4_switch:
      name: Relay 4 Switch
      default: []
      selector:
        entity:
          domain: [switch, light]
    relay_4_mode:
      name: Relay 4 Boot Mode
      default: "off"
      selector:
        select:
          options:
            - label: "On"
              value: "on"
            - label: "Off"
              value: "off"
    linked_device_4:
      name: Relay 4 Linked External Device
      default: []
      selector:
        entity: {}
    keep_linked_4_on:
      name: Keep Linked Device 4 ON?
      default: true
      selector:
        boolean: {}
    status_light:
      name: T5 Status Indicator Light
      default: []
      selector:
        entity:
          domain: light

mode: restart

variables:
  r1_m: !input relay_1_mode
  r2_s: !input relay_2_switch
  r2_m: !input relay_2_mode
  r3_s: !input relay_3_switch
  r3_m: !input relay_3_mode
  r4_s: !input relay_4_switch
  r4_m: !input relay_4_mode
  l_d1: !input linked_device_1
  k_l1: !input keep_linked_1_on
  l_d2: !input linked_device_2
  k_l2: !input keep_linked_2_on
  l_d3: !input linked_device_3
  k_l3: !input keep_linked_3_on
  l_d4: !input linked_device_4
  k_l4: !input keep_linked_4_on
  s_light: !input status_light
  i_delay: !input initial_delay
  s_delay: !input sync_delay

triggers:
  - platform: state
    entity_id: !input trigger_sensor
    from: "unavailable"

actions:
  - delay: "{{ i_delay }}"
  
  - parallel:
      - if:
          - condition: template
            value_template: "{{ r1_m == 'on' }}"
        then:
          - service: homeassistant.turn_on
            target:
              entity_id: !input relay_1_switch
          - if:
              - condition: template
                value_template: "{{ l_d1 != none and l_d1 != [] }}"
            then:
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input linked_device_1
                    not_from: [unavailable, unknown]
                timeout: "{{ s_delay }}"
                continue_on_timeout: true
              - service: homeassistant.turn_on
                target:
                  entity_id: !input linked_device_1
                continue_on_error: true
              - if:
                  - condition: template
                    value_template: "{{ not k_l1 }}"
                then:
                  - delay: "00:00:01"
                  - service: homeassistant.turn_off
                    target:
                      entity_id: !input linked_device_1
                    continue_on_error: true
        else:
          - service: homeassistant.turn_off
            target:
              entity_id: !input relay_1_switch

      - if:
          - condition: template
            value_template: "{{ r2_s != none and r2_s != [] }}"
        then:
          - if:
              - condition: template
                value_template: "{{ r2_m == 'on' }}"
            then:
              - service: homeassistant.turn_on
                target:
                  entity_id: !input relay_2_switch
              - if:
                  - condition: template
                    value_template: "{{ l_d2 != none and l_d2 != [] }}"
                then:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input linked_device_2
                        not_from: [unavailable, unknown]
                    timeout: "{{ s_delay }}"
                    continue_on_timeout: true
                  - service: homeassistant.turn_on
                    target:
                      entity_id: !input linked_device_2
                    continue_on_error: true
                  - if:
                      - condition: template
                        value_template: "{{ not k_l2 }}"
                    then:
                      - delay: "00:00:01"
                      - service: homeassistant.turn_off
                        target:
                          entity_id: !input linked_device_2
                        continue_on_error: true
            else:
              - service: homeassistant.turn_off
                target:
                  entity_id: !input relay_2_switch

      - if:
          - condition: template
            value_template: "{{ r3_s != none and r3_s != [] }}"
        then:
          - if:
              - condition: template
                value_template: "{{ r3_m == 'on' }}"
            then:
              - service: homeassistant.turn_on
                target:
                  entity_id: !input relay_3_switch
              - if:
                  - condition: template
                    value_template: "{{ l_d3 != none and l_d3 != [] }}"
                then:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input linked_device_3
                        not_from: [unavailable, unknown]
                    timeout: "{{ s_delay }}"
                    continue_on_timeout: true
                  - service: homeassistant.turn_on
                    target:
                      entity_id: !input linked_device_3
                    continue_on_error: true
                  - if:
                      - condition: template
                        value_template: "{{ not k_l3 }}"
                    then:
                      - delay: "00:00:01"
                      - service: homeassistant.turn_off
                        target:
                          entity_id: !input linked_device_3
                        continue_on_error: true
            else:
              - service: homeassistant.turn_off
                target:
                  entity_id: !input relay_3_switch

      - if:
          - condition: template
            value_template: "{{ r4_s != none and r4_s != [] }}"
        then:
          - if:
              - condition: template
                value_template: "{{ r4_m == 'on' }}"
            then:
              - service: homeassistant.turn_on
                target:
                  entity_id: !input relay_4_switch
              - if:
                  - condition: template
                    value_template: "{{ l_d4 != none and l_d4 != [] }}"
                then:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input linked_device_4
                        not_from: [unavailable, unknown]
                    timeout: "{{ s_delay }}"
                    continue_on_timeout: true
                  - service: homeassistant.turn_on
                    target:
                      entity_id: !input linked_device_4
                    continue_on_error: true
                  - if:
                      - condition: template
                        value_template: "{{ not k_l4 }}"
                    then:
                      - delay: "00:00:01"
                      - service: homeassistant.turn_off
                        target:
                          entity_id: !input linked_device_4
                        continue_on_error: true
            else:
              - service: homeassistant.turn_off
                target:
                  entity_id: !input relay_4_switch

  - if:
      - condition: template
        value_template: "{{ s_light != none and s_light != [] }}"
    then:
      - delay: "00:00:01"
      - service: light.turn_off
        target:
          entity_id: !input status_light