blueprint:
  name: TX Ultimate relay boot mode (1–4 gang, fixed naming)
  description: >
    Set per-relay boot behavior (Default / Force ON / Force OFF) for a
    Sonoff TX Ultimate using fixed naming:
      - Relays: switch.xxx_relay_1..4
      - Helpers: input_select.xxx_relay_1_boot_mode..4_boot_mode
    Supports 1/2/3/4‑gang devices.
  domain: automation
  author: you

  input:
    name_prefix:
      name: Name prefix (xxx)
      description: >
        Common name used for this switch. Relays must be:
          switch.xxx_relay_1..4
        and helpers must be:
          input_select.xxx_relay_1_boot_mode..4_boot_mode
      selector:
        text:

    gang_count:
      name: Gang count
      description: How many relays (gangs) this switch has
      default: 4
      selector:
        select:
          options:
            - 1
            - 2
            - 3
            - 4

mode: single

trigger:
  - platform: state
    entity_id:
      - "{{ 'switch.' ~ (name_prefix | string) ~ '_relay_1' }}"
      - "{{ 'switch.' ~ (name_prefix | string) ~ '_relay_2' }}"
      - "{{ 'switch.' ~ (name_prefix | string) ~ '_relay_3' }}"
      - "{{ 'switch.' ~ (name_prefix | string) ~ '_relay_4' }}"

variables:
  name_prefix: !input name_prefix
  gang_count: !input gang_count

  relay_1: "{{ 'switch.' ~ name_prefix ~ '_relay_1' }}"
  relay_2: "{{ 'switch.' ~ name_prefix ~ '_relay_2' }}"
  relay_3: "{{ 'switch.' ~ name_prefix ~ '_relay_3' }}"
  relay_4: "{{ 'switch.' ~ name_prefix ~ '_relay_4' }}"

  helper_1: "{{ 'input_select.' ~ name_prefix ~ '_relay_1_boot_mode' }}"
  helper_2: "{{ 'input_select.' ~ name_prefix ~ '_relay_2_boot_mode' }}"
  helper_3: "{{ 'input_select.' ~ name_prefix ~ '_relay_3_boot_mode' }}"
  helper_4: "{{ 'input_select.' ~ name_prefix ~ '_relay_4_boot_mode' }}"

action:
  - delay: "00:00:03"

  # Relay 1
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states(helper_1) == 'Force ON' }}"
        sequence:
          - condition: template
            value_template: "{{ states(relay_1) != 'on' }}"
          - service: switch.turn_on
            target:
              entity_id: "{{ relay_1 }}"
      - conditions:
          - condition: template
            value_template: "{{ states(helper_1) == 'Force OFF' }}"
        sequence:
          - condition: template
            value_template: "{{ states(relay_1) != 'off' }}"
          - service: switch.turn_off
            target:
              entity_id: "{{ relay_1 }}"
    default: []

  # Relay 2
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ gang_count|int >= 2 and states(helper_2) == 'Force ON' }}"
        sequence:
          - condition: template
            value_template: "{{ states(relay_2) != 'on' }}"
          - service: switch.turn_on
            target:
              entity_id: "{{ relay_2 }}"
      - conditions:
          - condition: template
            value_template: "{{ gang_count|int >= 2 and states(helper_2) == 'Force OFF' }}"
        sequence:
          - condition: template
            value_template: "{{ states(relay_2) != 'off' }}"
          - service: switch.turn_off
            target:
              entity_id: "{{ relay_2 }}"
    default: []

  # Relay 3
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ gang_count|int >= 3 and states(helper_3) == 'Force ON' }}"
        sequence:
          - condition: template
            value_template: "{{ states(relay_3) != 'on' }}"
          - service: switch.turn_on
            target:
              entity_id: "{{ relay_3 }}"
      - conditions:
          - condition: template
            value_template: "{{ gang_count|int >= 3 and states(helper_3) == 'Force OFF' }}"
        sequence:
          - condition: template
            value_template: "{{ states(relay_3) != 'off' }}"
          - service: switch.turn_off
            target:
              entity_id: "{{ relay_3 }}"
    default: []

  # Relay 4
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ gang_count|int >= 4 and states(helper_4) == 'Force ON' }}"
        sequence:
          - condition: template
            value_template: "{{ states(relay_4) != 'on' }}"
          - service: switch.turn_on
            target:
              entity_id: "{{ relay_4 }}"
      - conditions:
          - condition: template
            value_template: "{{ gang_count|int >= 4 and states(helper_4) == 'Force OFF' }}"
        sequence:
          - condition: template
            value_template: "{{ states(relay_4) != 'off' }}"
          - service: switch.turn_off
            target:
              entity_id: "{{ relay_4 }}"
    default: []
