blueprint:
  name: Multi-channel Relay Boot State Restorer (Flexible 1-4 Gang)
  description: >
    Automatically restores relay states based on input_select at boot. 
    Supports 1 to 4 channels. Leave unused channels blank.
  domain: automation
  input:
    trigger_sensor:
      name: Device Connection Status Sensor
      description: The sensor used to trigger the automation (e.g., Device Name Sensor).
      selector:
        entity:
          domain: sensor
    
    # Relay 1 (Required)
    relay_1_switch:
      name: Relay 1 Switch
      selector:
        entity:
          domain: switch
    relay_1_mode:
      name: Relay 1 Boot Mode Input
      selector:
        entity:
          domain: input_select

    # Relay 2 (Optional)
    relay_2_switch:
      name: Relay 2 Switch (Optional)
      default: []
      selector:
        entity:
          domain: switch
    relay_2_mode:
      name: Relay 2 Boot Mode Input (Optional)
      default: []
      selector:
        entity:
          domain: input_select

    # Relay 3 (Optional)
    relay_3_switch:
      name: Relay 3 Switch (Optional)
      default: []
      selector:
        entity:
          domain: switch
    relay_3_mode:
      name: Relay 3 Boot Mode Input (Optional)
      default: []
      selector:
        entity:
          domain: input_select

    # Relay 4 (Optional)
    relay_4_switch:
      name: Relay 4 Switch (Optional)
      default: []
      selector:
        entity:
          domain: switch
    relay_4_mode:
      name: Relay 4 Boot Mode Input (Optional)
      default: []
      selector:
        entity:
          domain: input_select

    # Status Light (Optional)
    status_light:
      name: Status Indicator Light (Optional)
      default: []
      selector:
        entity:
          domain: light

mode: restart

# Define variables to check if optional inputs are provided
variables:
  r2_s: !input relay_2_switch
  r3_s: !input relay_3_switch
  r4_s: !input relay_4_switch
  s_light: !input status_light

trigger:
  - platform: state
    entity_id: !input trigger_sensor
    from: "unavailable"

action:
  - delay: "00:00:05"
  
  # --- Channel 1 (Always Executed) ---
  - choose:
      - conditions:
          - condition: state
            entity_id: !input relay_1_mode
            state: "on"
          - condition: not
            conditions:
              - condition: state
                entity_id: !input relay_1_switch
                state: "on"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input relay_1_switch
      - conditions:
          - condition: state
            entity_id: !input relay_1_mode
            state: "off"
          - condition: not
            conditions:
              - condition: state
                entity_id: !input relay_1_switch
                state: "off"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input relay_1_switch

  # --- Channel 2 (Only if configured) ---
  - if:
      - condition: template
        value_template: "{{ r2_s != none and r2_s != [] }}"
    then:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input relay_2_mode
                state: "on"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_2_switch
                    state: "on"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: !input relay_2_switch
          - conditions:
              - condition: state
                entity_id: !input relay_2_mode
                state: "off"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_2_switch
                    state: "off"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: !input relay_2_switch

  # --- Channel 3 (Only if configured) ---
  - if:
      - condition: template
        value_template: "{{ r3_s != none and r3_s != [] }}"
    then:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input relay_3_mode
                state: "on"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_3_switch
                    state: "on"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: !input relay_3_switch
          - conditions:
              - condition: state
                entity_id: !input relay_3_mode
                state: "off"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_3_switch
                    state: "off"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: !input relay_3_switch

  # --- Channel 4 (Only if configured) ---
  - if:
      - condition: template
        value_template: "{{ r4_s != none and r4_s != [] }}"
    then:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input relay_4_mode
                state: "on"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_4_switch
                    state: "on"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: !input relay_4_switch
          - conditions:
              - condition: state
                entity_id: !input relay_4_mode
                state: "off"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_4_switch
                    state: "off"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: !input relay_4_switch

  # --- Final Light Action (Only if configured) ---
  - if:
      - condition: template
        value_template: "{{ s_light != none and s_light != [] }}"
    then:
      - delay: "00:00:01"
      - service: light.turn_off
        target:
          entity_id: !input status_light