blueprint:
  name: TX Ultimate relay boot mode (1–4 gang)
  description: >
    Set per-relay boot behavior (ON / OFF) for a Sonoff TX Ultimate
    using input_select helpers. Supports 1/2/3/4‑gang devices.
    Triggers when T5 comes online (device_name sensor from unavailable to any state).
    For each relay, create an input_select with options:
      - "on"
      - "off"
  domain: automation
  author: you

  input:
    device_state_entity:
      name: T5 device_name sensor
      description: >
        Sensor entity like sensor.t5_4c_03_device_name.
        Automation triggers when this changes from unavailable to any state.
      selector:
        entity:
          domain: sensor

    gang_count:
      name: Gang count
      description: How many relays (gangs) does this switch have
      default: "4"
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"
            - "4"

    relay_1:
      name: Relay 1 entity
      description: First relay/light (required)
      selector:
        entity:
          domain:
            - switch
            - light

    relay_2:
      name: Relay 2 entity
      description: Second relay/light (leave empty if 1‑gang)
      default: ""
      selector:
        entity:
          domain:
            - switch
            - light

    relay_3:
      name: Relay 3 entity
      description: Third relay/light (leave empty if 1/2‑gang)
      default: ""
      selector:
        entity:
          domain:
            - switch
            - light

    relay_4:
      name: Relay 4 entity
      description: Fourth relay/light (leave empty if 1/2/3‑gang)
      default: ""
      selector:
        entity:
          domain:
            - switch
            - light

    helper_1:
      name: Relay 1 boot-mode helper
      description: input_select for relay 1 boot mode (values must be "on" or "off")
      selector:
        entity:
          domain: input_select

    helper_2:
      name: Relay 2 boot-mode helper
      description: input_select for relay 2 boot mode (optional)
      default: ""
      selector:
        entity:
          domain: input_select

    helper_3:
      name: Relay 3 boot-mode helper
      description: input_select for relay 3 boot mode (optional)
      default: ""
      selector:
        entity:
          domain: input_select

    helper_4:
      name: Relay 4 boot-mode helper
      description: input_select for relay 4 boot mode (optional)
      default: ""
      selector:
        entity:
          domain: input_select

mode: restart

# Trigger when T5 comes online: device_name sensor from unavailable to any state
triggers:
  - entity_id: !input device_state_entity
    from:
      - unavailable
    to: null
    trigger: state

variables:
  gang_count: "{{ inputs.gang_count | int(4) }}"
  relay_1: !input relay_1
  relay_2: !input relay_2
  relay_3: !input relay_3
  relay_4: !input relay_4
  helper_1: !input helper_1
  helper_2: !input helper_2
  helper_3: !input helper_3
  helper_4: !input helper_4

action:
  # Let the device finish its own restore logic
  - delay: "00:00:03"

  # ------- Relay 1 (always present) -------
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states(helper_1) == 'on' }}"
        sequence:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ states(relay_1) == 'on' }}"
          - action: homeassistant.turn_on
            target:
              entity_id: "{{ relay_1 }}"
      - conditions:
          - condition: template
            value_template: "{{ states(helper_1) == 'off' }}"
        sequence:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ states(relay_1) == 'off' }}"
          - action: homeassistant.turn_off
            target:
              entity_id: "{{ relay_1 }}"
    default: []

  - delay: "00:00:01"

  # ------- Relay 2 (only if gang_count >= 2) -------
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ gang_count >= 2 and relay_2 != '' and helper_2 != '' and states(helper_2) == 'on' }}"
        sequence:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ states(relay_2) == 'on' }}"
          - action: homeassistant.turn_on
            target:
              entity_id: "{{ relay_2 }}"
      - conditions:
          - condition: template
            value_template: "{{ gang_count >= 2 and relay_2 != '' and helper_2 != '' and states(helper_2) == 'off' }}"
        sequence:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ states(relay_2) == 'off' }}"
          - action: homeassistant.turn_off
            target:
              entity_id: "{{ relay_2 }}"
    default: []

  - delay: "00:00:01"

  # ------- Relay 3 (only if gang_count >= 3) -------
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ gang_count >= 3 and relay_3 != '' and helper_3 != '' and states(helper_3) == 'on' }}"
        sequence:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ states(relay_3) == 'on' }}"
          - action: homeassistant.turn_on
            target:
              entity_id: "{{ relay_3 }}"
      - conditions:
          - condition: template
            value_template: "{{ gang_count >= 3 and relay_3 != '' and helper_3 != '' and states(helper_3) == 'off' }}"
        sequence:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ states(relay_3) == 'off' }}"
          - action: homeassistant.turn_off
            target:
              entity_id: "{{ relay_3 }}"
    default: []

  - delay: "00:00:01"

  # ------- Relay 4 (only if gang_count >= 4) -------
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ gang_count >= 4 and relay_4 != '' and helper_4 != '' and states(helper_4) == 'on' }}"
        sequence:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ states(relay_4) == 'on' }}"
          - action: homeassistant.turn_on
            target:
              entity_id: "{{ relay_4 }}"
      - conditions:
          - condition: template
            value_template: "{{ gang_count >= 4 and relay_4 != '' and helper_4 != '' and states(helper_4) == 'off' }}"
        sequence:
          - condition: not
            conditions:
              - condition: template
                value_template: "{{ states(relay_4) == 'off' }}"
          - action: homeassistant.turn_off
            target:
              entity_id: "{{ relay_4 }}"
    default: []
