blueprint:
  name: TX Ultimate relay boot mode (1–4 gang)
  description: >
    Set per-relay boot behavior (Default / Force ON / Force OFF) for a
    Sonoff TX Ultimate using helpers. Supports 1/2/3/4‑gang devices.
    For each relay, create an input_select with options:
      - Default
      - Force ON
      - Force OFF
  domain: automation
  author: you

  input:
    gang_count:
      name: Gang count
      description: How many relays (gangs) this switch has
      default: "4"
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"
            - "4"

    relay_1:
      name: Relay 1 entity
      description: First relay/light (required)
      selector:
        entity:
          domain:
            - switch
            - light

    relay_2:
      name: Relay 2 entity
      description: Second relay/light (leave empty if 1‑gang)
      default: ""
      selector:
        entity:
          domain:
            - switch
            - light

    relay_3:
      name: Relay 3 entity
      description: Third relay/light (leave empty if 1/2‑gang)
      default: ""
      selector:
        entity:
          domain:
            - switch
            - light

    relay_4:
      name: Relay 4 entity
      description: Fourth relay/light (leave empty if 1/2/3‑gang)
      default: ""
      selector:
        entity:
          domain:
            - switch
            - light

    helper_1:
      name: Relay 1 boot-mode helper
      description: input_select for relay 1 boot mode
      selector:
        entity:
          domain: input_select

    helper_2:
      name: Relay 2 boot-mode helper
      description: input_select for relay 2 boot mode (optional)
      default: ""
      selector:
        entity:
          domain: input_select

    helper_3:
      name: Relay 3 boot-mode helper
      description: input_select for relay 3 boot mode (optional)
      default: ""
      selector:
        entity:
          domain: input_select

    helper_4:
      name: Relay 4 boot-mode helper
      description: input_select for relay 4 boot mode (optional)
      default: ""
      selector:
        entity:
          domain: input_select

mode: single

trigger:
  - platform: state
    entity_id:
      - !input relay_1
      - !input relay_2
      - !input relay_3
      - !input relay_4

variables:
  gang_count: "{{ (inputs.gang_count | default('4')) | int }}"
  relay_1: "{{ inputs.relay_1 }}"
  relay_2: "{{ inputs.relay_2 }}"
  relay_3: "{{ inputs.relay_3 }}"
  relay_4: "{{ inputs.relay_4 }}"
  helper_1: "{{ inputs.helper_1 }}"
  helper_2: "{{ inputs.helper_2 }}"
  helper_3: "{{ inputs.helper_3 }}"
  helper_4: "{{ inputs.helper_4 }}"


action:
  # Let the device finish its own restore logic
  - delay: "00:00:03"

  # Relay 1 (always present)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states(helper_1) == 'Force ON' }}"
        sequence:
          - condition: template
            value_template: "{{ states(relay_1) != 'on' }}"
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ relay_1 }}"
      - conditions:
          - condition: template
            value_template: "{{ states(helper_1) == 'Force OFF' }}"
        sequence:
          - condition: template
            value_template: "{{ states(relay_1) != 'off' }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ relay_1 }}"
    default: []

  # Relay 2 (only if gang_count >= 2 and helper_2 is set)
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ gang_count >= 2 and helper_2 != '' and states(helper_2) == 'Force ON' }}
        sequence:
          - condition: template
            value_template: "{{ states(relay_2) != 'on' }}"
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ relay_2 }}"
      - conditions:
          - condition: template
            value_template: >
              {{ gang_count >= 2 and helper_2 != '' and states(helper_2) == 'Force OFF' }}
        sequence:
          - condition: template
            value_template: "{{ states(relay_2) != 'off' }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ relay_2 }}"
    default: []

  # Relay 3 (only if gang_count >= 3 and helper_3 is set)
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ gang_count >= 3 and helper_3 != '' and states(helper_3) == 'Force ON' }}
        sequence:
          - condition: template
            value_template: "{{ states(relay_3) != 'on' }}"
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ relay_3 }}"
      - conditions:
          - condition: template
            value_template: >
              {{ gang_count >= 3 and helper_3 != '' and states(helper_3) == 'Force OFF' }}
        sequence:
          - condition: template
            value_template: "{{ states(relay_3) != 'off' }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ relay_3 }}"
    default: []

  # Relay 4 (only if gang_count >= 4 and helper_4 is set)
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ gang_count >= 4 and helper_4 != '' and states(helper_4) == 'Force ON' }}
        sequence:
          - condition: template
            value_template: "{{ states(relay_4) != 'on' }}"
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ relay_4 }}"
      - conditions:
          - condition: template
            value_template: >
              {{ gang_count >= 4 and helper_4 != '' and states(helper_4) == 'Force OFF' }}
        sequence:
          - condition: template
            value_template: "{{ states(relay_4) != 'off' }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ relay_4 }}"
    default: []
