blueprint:
  name: "TX-Ultimate-Easy Enhanced Boot Restorer"
  description: |
    ### (Version: 1.1.7)
    
    This blueprint acts as a dynamic management layer for the **TX-Ultimate-Easy** (by edwardtfn). While the ESPHome firmware handles local hardware logic, this blueprint provides:
    
    * **1. Dynamic Boot Logic**: Change relay boot states (on/off) via HA UI without re-flashing.
    * **2. Reconnection Sync**: Specifically handles state restoration when the device recovers from 'unavailable'.
    * **3. Status Cleanup**: Automatically turns off the LED indicator/ring after the sequence completes.
    * **4. Network Optimization**: Only sends commands if the current state differs from the target.
    
    ---
    **汳｡ Setup Tip**: You can create the required `input_select` helpers directly within the automation setup screen by clicking the **"+"** button at the bottom of the dropdown menu.
    
    **Note**: This blueprint's logic and structure were developed and optimized with the assistance of AI (Gemini). 
    Supports 1 to 4 channels. Unused channels can be left blank.
  domain: automation
  source_url: https://github.com/MarcusTseng/tx-ultimate-relay-boot-mode/blob/main/blueprints/automation/tx_boot_mode/tx_relay_boot_mode.yaml
  author: Marcus Tseng
  homeassistant:
    min_version: 2023.8.0
  input:
    trigger_sensor:
      name: Device Connectivity Sensor
      description: The 'Device Name' sensor provided by TX-Ultimate-Easy (e.g., sensor.t5_device_name).
      selector:
        entity:
          domain: sensor
    relay_1_switch:
      name: Relay 1 Switch
      description: 
        switch or light entity for relay 1 based on your configuration
      selector:
        entity:
          domain: 
            - switch
            - light
    relay_1_mode:
      name: Relay 1 Boot Mode Helper
      description: 
        input_select for relay 1 boot mode (values must be "on" or "off")
      selector:
        entity:
          domain: input_select
    relay_2_switch:
      name: Relay 2 Switch (Optional, leave empty if 1窶組ang)
      default: []
      selector:
        entity:
          domain: 
            - switch
            - light
    relay_2_mode:
      name: Relay 2 Boot Mode Helper (Optional, leave empty if 1窶組ang)
      default: []
      selector:
        entity:
          domain: input_select
    relay_3_switch:
      name: Relay 3 Switch (Optional, leave empty if 1/2窶組ang)
      default: []
      selector:
        entity:
          domain: 
            - switch
            - light
    relay_3_mode:
      name: Relay 3 Boot Mode Helper (Optional, leave empty if 1/2窶組ang)
      default: []
      selector:
        entity:
          domain: input_select
    relay_4_switch:
      name: Relay 4 Switch (Optional, leave empty if 1/2/3窶組ang)
      default: []
      selector:
        entity:
          domain: 
            - switch
            - light
    relay_4_mode:
      name: Relay 4 Boot Mode Helper (Optional, leave empty if 1/2/3窶組ang)
      default: []
      selector:
        entity:
          domain: input_select
    status_light:
      name: T5 Status Indicator Light
      default: []
      selector:
        entity:
          domain: light

mode: restart

variables:
  r2_s: !input relay_2_switch
  r3_s: !input relay_3_switch
  r4_s: !input relay_4_switch
  s_light: !input status_light

trigger:
  - platform: state
    entity_id: !input trigger_sensor
    from: "unavailable"

action:
  - delay: "00:00:05"
  
  # --- Channel 1 ---
  - choose:
      - conditions:
          - condition: state
            entity_id: !input relay_1_mode
            state: "on"
          - condition: not
            conditions:
              - condition: state
                entity_id: !input relay_1_switch
                state: "on"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input relay_1_switch
      - conditions:
          - condition: state
            entity_id: !input relay_1_mode
            state: "off"
          - condition: not
            conditions:
              - condition: state
                entity_id: !input relay_1_switch
                state: "off"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input relay_1_switch

  # --- Channel 2 ---
  - if:
      - condition: template
        value_template: "{{ r2_s != none and r2_s != [] }}"
    then:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input relay_2_mode
                state: "on"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_2_switch
                    state: "on"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: !input relay_2_switch
          - conditions:
              - condition: state
                entity_id: !input relay_2_mode
                state: "off"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_2_switch
                    state: "off"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: !input relay_2_switch

  # --- Channel 3 ---
  - if:
      - condition: template
        value_template: "{{ r3_s != none and r3_s != [] }}"
    then:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input relay_3_mode
                state: "on"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_3_switch
                    state: "on"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: !input relay_3_switch
          - conditions:
              - condition: state
                entity_id: !input relay_3_mode
                state: "off"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_3_switch
                    state: "off"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: !input relay_3_switch

  # --- Channel 4 ---
  - if:
      - condition: template
        value_template: "{{ r4_s != none and r4_s != [] }}"
    then:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input relay_4_mode
                state: "on"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_4_switch
                    state: "on"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: !input relay_4_switch
          - conditions:
              - condition: state
                entity_id: !input relay_4_mode
                state: "off"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input relay_4_switch
                    state: "off"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: !input relay_4_switch

  - if:
      - condition: template
        value_template: "{{ s_light != none and s_light != [] }}"
    then:
      - delay: "00:00:01"
      - service: light.turn_off
        target:
          entity_id: !input status_light