blueprint:
  name: "Enhanced Boot Restorer for TX-Ultimate-Easy"
  description: >
    This blueprint enhances the **TX-Ultimate-Easy** (by edwardtfn) functionality. 
    While TX-Ultimate-Easy manages the hardware, this blueprint provides a 
    dynamic Home Assistant management layer to:
    
    1. Restore 1-4 channel relay states based on UI-editable Helpers (input_select).
    2. Synchronize states specifically when the device recovers from an 'unavailable' status.
    3. Automatically turn off the status indicator light after the boot sequence.
    
    Note: Requires 'input_select' helpers for each channel with 'on' and 'off' options.
  version: 1.1.0
  domain: automation
  source_url: https://github.com/YOUR_USERNAME/YOUR_REPO/blob/main/relay_boot_restorer.yaml
  author: YourName
  homeassistant:
    min_version: 2023.8.0
  input:
    trigger_sensor:
      name: Device Connectivity Sensor
      description: The 'Device Name' sensor from your TX-Ultimate-Easy entity list.
      selector:
        entity:
          domain: sensor
    
    # Relay 1 (Required)
    relay_1_switch:
      name: Relay 1 Switch
      selector:
        entity:
          domain: switch
    relay_1_mode:
      name: Relay 1 Boot Mode Helper
      description: Create a helper with options 'on' and 'off'.
      selector:
        entity:
          domain: input_select

    # Relay 2 (Optional)
    relay_2_switch:
      name: Relay 2 Switch (Optional)
      default: []
      selector:
        entity:
          domain: switch
    relay_2_mode:
      name: Relay 2 Boot Mode Helper (Optional)
      default: []
      selector:
        entity:
          domain: input_select

    # Relay 3 (Optional)
    relay_3_switch:
      name: Relay 3 Switch (Optional)
      default: []
      selector:
        entity:
          domain: switch
    relay_3_mode:
      name: Relay 3 Boot Mode Helper (Optional)
      default: []
      selector:
        entity:
          domain: input_select

    # Relay 4 (Optional)
    relay_4_switch:
      name: Relay 4 Switch (Optional)
      default: []
      selector:
        entity:
          domain: switch
    relay_4_mode:
      name: Relay 4 Boot Mode Helper (Optional)
      default: []
      selector:
        entity:
          domain: input_select

    # Status Light (Optional)
    status_light:
      name: T5 Status Indicator Light
      description: The light entity for the TX Ultimate ring/indicator.
      default: []
      selector:
        entity:
          domain: light

mode: restart

variables:
  r2_s: !input relay_2_switch
  r3_s: !input relay_3_switch
  r4_s: !input relay_4_switch
  s_light: !input status_light

trigger:
  - platform: state
    entity_id: !input trigger_sensor
    from: "unavailable"

action:
  - delay: "00:00:05"
  
  # Logic for Channel 1 to 4 remains the same...
  # [Omitted here for brevity, keep the logic from the previous turn]

  - if:
      - condition: template
        value_template: "{{ s_light != none and s_light != [] }}"
    then:
      - delay: "00:00:01"
      - service: light.turn_off
        target:
          entity_id: !input status_light